import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Topbar from "@/app/components/TopBar";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body cz-shortcut-listen="true" className="__variable_188709 __variable_9a8899 antialiased" >
        <Topbar/>
        <Navbar/>
        {/* <ThemeToggle/> */}
        {children}
      <Footer/>
      </body>
    </html>
  );
}
